apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
      - image: mikaelsouza/atmosphere-client-secure
        name: client
        resources: {}
        command: ["/bin/ash"]
        args: ["-c", "sleep 7200"]

      restartPolicy: Always
status: {}
