#########################################################
##
## Vallum DB
##
#########################################################

apiVersion: v1
kind: Pod
metadata:
  name: vallum-db
  labels:
    app: vallum-db
spec:
    nodeSelector:
      region: brazil
    containers:
    - env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sqlpass
            key: password
      - name: MYSQL_ROOT_HOST
        value: '%'
      - name: MYSQL_DATABASE
        value: vallum
      image: ronnypeterson/vallum-db-local
      imagePullPolicy: Always
      name: vallum-db
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: vallum-db
spec:
  selector:
    app: vallum-db
  ports:
  - protocol: TCP
    port: 22
    name: ssh
    targetPort: 22
  - protocol: TCP
    port: 3306
    name: mysql
    targetPort: 3306
---

#########################################################
##
## Vallum Repo
##
#########################################################

apiVersion: v1
kind: Pod
metadata:
  name: vallum-repo
  labels:
    app: vallum-repo
spec:
  nodeSelector:
    region: brazil
  containers:
  - image: ronnypeterson/vallum-repo-local
    imagePullPolicy: Always
    name: vallum-repo
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sqlpass
          key: password
    - name: MYSQL_ROOT_HOST
      value: '%'
    - name: MYSQL_DATABASE
      value: samples
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: vallum-repo
spec:
  selector:
    app: vallum-repo
  ports:
  - protocol: TCP
    port: 22
    name: ssh
    targetPort: 22
  - protocol: TCP
    port: 3306
    name: mysql
    targetPort: 3306
---

#########################################################
##
## Vallum Audit-local
##
#########################################################

apiVersion: v1
kind: Pod
metadata:
  name: vallum-audit
  labels:
    app: vallum-audit
spec: 
  nodeSelector:
    region: brazil
  containers:
  - image: ronnypeterson/vallum-audit-local
    imagePullPolicy: Always
    name: vallum-audit
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: vallum-audit
spec:
  selector:
    app: vallum-audit
  ports:
  - protocol: TCP
    port: 22
    name: ssh
    targetPort: 22
  - protocol: TCP
    port: 9004
    name: vallum-audit
    targetPort: 9004 
---

#########################################################
##
## Vallum Privacy
##
#########################################################

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: vallum-privacy
  labels:
     app: vallum-privacy
spec:
  nodeSelector:
    region: brazil
  containers:
  - image: ronnypeterson/vallum-privacy-local
    imagePullPolicy: Always
    name: vallum-privacy
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: vallum-privacy
spec:
  selector:
    app: vallum-privacy
  ports:
  - protocol: TCP
    port: 22
    name: ssh
    targetPort: 22
  - protocol: TCP
    port: 9002
    name: vallum-privacy
    targetPort: 9002
---


#########################################################
##
## Vallum local
##
#########################################################

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: vallum
  labels:
    app: vallum
spec:
  nodeSelector:
    region: brazil
  containers:
  - image: ronnypeterson/vallum-local
    imagePullPolicy: Always
    name: vallum
---
##
## DB Statful Set
##
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: vallum
spec:
  selector:
    app: vallum
  ports:
  - protocol: TCP
    port: 9000
    name: vallum
    targetPort: 9000
  - protocol: TCP
    port: 22
    name: ssh
    targetPort: 22
