
#########################################################
##
## Secret key
##
#########################################################

apiVersion: v1
kind: Secret
metadata:
  name: sqlpass
data:
# echo -n '#s3nh@#' | base64 
  password: I3MzbmhAIw==
---

#########################################################
##
## Vallum Audit-db
##
#########################################################

apiVersion: v1
kind: Pod
metadata:
  name: vallum-audit-db
  labels:
    app: vallum-audit-db
spec:
  containers:
  - image: ronnypeterson/vallum-audit-db
    imagePullPolicy: Always
    name: vallum-audit-db
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sqlpass
          key: password
    - name: MYSQL_ROOT_HOST
      value: '%'
    - name: MYSQL_DATABASE
      value: vallum_audit
  nodeSelector:
    aes: "true"
    region: brazil

---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: vallum-audit-db
spec:
  selector:
    app: vallum-audit-db
  ports:
  - protocol: TCP
    port: 22
    name: ssh
    targetPort: 22
  - protocol: TCP
    port: 3306
    name: mysql
    targetPort: 3306
